"""Excel exports (openpyxl) - formatted, filterable, with a report information sheet."""
from __future__ import annotations

from datetime import datetime

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from .. import APP_NAME, __version__
from ..analysis.metrics import lookahead
from ..analysis.columns import COLUMNS
from . import style as S

HDR_FILL = PatternFill("solid", fgColor=S.SAR_BLUE.lstrip("#"))
HDR_FONT = Font(bold=True, color="FFFFFF")
TITLE_FONT = Font(bold=True, size=14, color=S.SAR_BLUE.lstrip("#"))

FULL_COLS = ["code", "name", "wbs", "phase", "conf", "level", "stage", "discipline", "location", "contractor", "wp",
             "orig", "rem", "bl_dur", "bl_start", "bl_finish", "start", "finish", "act_start", "act_finish", "pct",
             "tf", "ff", "start_var", "finish_var", "dur_var", "status", "p6status", "critical", "match", "match_conf",
             "weight", "budget", "actual_cost"]
LOOKAHEAD_COLS = ["code", "name", "wbs", "discipline", "bl_start", "bl_finish", "start", "finish", "status", "pct", "tf"]
CRIT_COLS = ["code", "name", "wbs", "phase", "start", "finish", "rem", "tf", "ff", "finish_var", "critical", "status"]


def _header(ws, headers: list[str], row: int = 1) -> None:
    for i, h in enumerate(headers, start=1):
        c = ws.cell(row=row, column=i, value=h)
        c.fill, c.font = HDR_FILL, HDR_FONT
        c.alignment = Alignment(vertical="center", wrap_text=True)
    ws.freeze_panes = ws.cell(row=row + 1, column=1)


def _widths(ws, headers: list[str], widths: dict | None = None) -> None:
    for i, h in enumerate(headers, start=1):
        w = (widths or {}).get(h) or min(60, max(10, len(h) + 2))
        ws.column_dimensions[get_column_letter(i)].width = w


def _cell_value(v, kind):
    if v is None:
        return None
    if kind == "date":
        return v.replace(tzinfo=None) if isinstance(v, datetime) else v
    if kind == "pct":
        return round(v / 100.0, 4)
    return v


def rows_sheet(ws, rows, cols, dd) -> None:
    headers = [COLUMNS[c][0] for c in cols]
    _header(ws, headers)
    for ri, r in enumerate(rows, start=2):
        for ci, c in enumerate(cols, start=1):
            _h, fn, kind = COLUMNS[c]
            cell = ws.cell(row=ri, column=ci, value=_cell_value(fn(r, dd), kind))
            if kind == "date":
                cell.number_format = "dd-mmm-yyyy"
            elif kind == "pct":
                cell.number_format = "0%"
            elif kind in ("num", "var"):
                cell.number_format = "0.0"
            elif kind == "money":
                cell.number_format = "#,##0"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(cols))}{max(1, len(rows) + 1)}"
    _widths(ws, headers, {"Activity Name": 45, "WBS": 40, "Activity ID": 14})


def info_sheet(wb: Workbook, title: str, ctx, extra: list[tuple[str, str]] = ()) -> None:
    ws = wb.active
    ws.title = "Report Info"
    ws["A1"] = "SAR"
    ws["A1"].font = Font(bold=True, size=20, color=S.SAR_BLUE.lstrip("#"))
    ws["A2"] = f"PROJECT CONTROLS DASHBOARD - {title}"
    ws["A2"].font = TITLE_FONT
    info = [("Project", f"{ctx.cur.project.name} ({ctx.cur.project.short_name})"),
            ("Data Date (Current)", ctx.data_date), ("Data Date (Baseline)", ctx.bl_data_date),
            ("Current Schedule File", ctx.cur.source_name), ("Baseline File", ctx.bl.source_name),
            ("Generated", datetime.now()), ("Generated by", f"{APP_NAME} v{__version__}"),
            ("Progress measure", ctx.measure), ("Weighting", ctx.weighting)] + list(extra)
    for i, (k, v) in enumerate(info, start=4):
        ws.cell(row=i, column=1, value=k).font = Font(bold=True)
        c = ws.cell(row=i, column=2, value=v)
        if isinstance(v, datetime):
            c.number_format = "dd-mmm-yyyy hh:mm"
    r = len(info) + 6
    ws.cell(row=r, column=1, value="Method notes").font = Font(bold=True)
    for i, n in enumerate(ctx.method_notes, start=r + 1):
        ws.cell(row=i, column=1, value=n)
    ws.column_dimensions["A"].width = 28
    ws.column_dimensions["B"].width = 70


def write_rows_workbook(path, title: str, rows, cols, dd) -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = title[:31] or "Activities"
    rows_sheet(ws, rows, cols, dd)
    wb.save(path)


def _kpi_sheet(wb, d) -> None:
    ws = wb.create_sheet("KPI Summary")
    headers = ["KPI", "Value", "Available", "Formula", "Source", "Method", "Activities included", "Notes"]
    _header(ws, headers)
    for i, (k, v) in enumerate(d.kpis.items(), start=2):
        ws.append([v.title, v.display, "Yes" if v.available else "No", v.formula, v.source, v.method, len(v.keys),
                   " | ".join(v.notes)])
    _widths(ws, headers, {"KPI": 28, "Formula": 60, "Source": 50, "Notes": 70, "Method": 30})


def _evm_sheet(wb, d) -> None:
    ws = wb.create_sheet("Earned Value")
    _header(ws, ["Metric", "Value", "Formula"])
    e = d.evm
    rows = [("BAC", e.get("BAC"), "Σ baseline budget cost"), ("PV", e.get("PV"), "Σ baseline budget × planned fraction at Data Date"),
            ("EV", e.get("EV"), "Σ baseline budget × % complete"), ("AC", e.get("AC"), "Σ actual cost (current)"),
            ("SV", e.get("SV"), "EV − PV"), ("CV", e.get("CV"), "EV − AC"), ("SPI", e.get("SPI"), "EV / PV"),
            ("CPI", e.get("CPI"), "EV / AC"), ("EAC", e.get("EAC"), "BAC / CPI"),
            ("EAC (bottom-up)", e.get("EAC_bottom_up"), "AC + Σ remaining cost"), ("ETC", e.get("ETC"), "EAC − AC"),
            ("VAC", e.get("VAC"), "BAC − EAC")]
    for m, v, f in rows:
        ws.append([m, "N/A" if v is None else v, f])
    for n in e.get("notes", []):
        ws.append(["Note", n])
    _widths(ws, ["Metric", "Value", "Formula"], {"Metric": 20, "Value": 20, "Formula": 50})
    if d.cost.get("available"):
        ws2 = wb.create_sheet("Cost by Group")
        hdr = [d.cost["dimension"], "Baseline Budget", "Current Budget", "Actual", "Forecast (AC+Remaining)"]
        _header(ws2, hdr)
        for g in d.cost["groups"]:
            ws2.append([g["group"], g["budget"], g["current_budget"], g["actual"], g["forecast"]])
        _widths(ws2, hdr, {hdr[0]: 30})


def _health_sheet(wb, checks) -> None:
    ws = wb.create_sheet("Schedule Health")
    hdr = ["Check", "Name", "Description", "Population", "Count", "Metric", "Threshold", "Result", "Basis", "Activities"]
    _header(ws, hdr)
    for c in checks:
        ws.append([c.id, c.name, c.description, c.population, c.count, c.metric_display, c.threshold, c.result, c.basis,
                   ", ".join(c.keys[:50]) + (" …" if len(c.keys) > 50 else "")])
    _widths(ws, hdr, {"Description": 50, "Name": 26, "Basis": 40, "Activities": 60})


def _validation_sheet(wb, findings, score) -> None:
    ws = wb.create_sheet("Data Validation")
    ws.append([f"Data quality score: {score} / 100 (100 minus listed penalties)"])
    _header(ws, ["Severity", "Category", "Finding", "Count", "Penalty", "Impact"], row=2)
    for f in findings:
        ws.append([f.severity, f.category, f.message, f.count, f.penalty, f.impact])
    _widths(ws, ["Severity", "Category", "Finding", "Count", "Penalty", "Impact"], {"Finding": 80, "Impact": 50, "Category": 24})


def _changes_sheet(wb, changes) -> None:
    ws = wb.create_sheet("Baseline Comparison")
    hdr = ["Change Category", "Baseline ID", "Current ID", "Activity Name", "Match Status", "Confidence", "Detail"]
    _header(ws, hdr)
    for cat, items in changes.items():
        for it in items:
            ws.append([cat, it["bl_code"], it["code"], it["name"], it["status"], it["confidence"], it["detail"]])
    _widths(ws, hdr, {"Activity Name": 40, "Detail": 70, "Change Category": 24})


def _milestone_sheet(wb, ms) -> None:
    ws = wb.create_sheet("Milestones")
    hdr = ["Activity ID", "Milestone", "Baseline Date", "Current Date", "Variance (d)", "Status"]
    _header(ws, hdr)
    for m in ms:
        ws.append([m["code"], m["name"], m["bl_date"], m["date"], m["variance"], m["status"]])
        for c in (3, 4):
            ws.cell(row=ws.max_row, column=c).number_format = "dd-mmm-yyyy"
    _widths(ws, hdr, {"Milestone": 40})


def _audit_sheet(wb, audit) -> None:
    ws = wb.create_sheet("Audit Trail")
    hdr = ["Time", "User", "Action", "Target", "Old", "New", "Note"]
    _header(ws, hdr)
    for a in audit:
        ws.append([a["time"], a["user"], a["action"], a["target"], a["old"], a["new"], a["note"]])
    _widths(ws, hdr, {"New": 60, "Note": 50, "Target": 30})


def export_detailed(path, d, cache, audit: list | None = None) -> None:
    ctx = d.ctx
    wb = Workbook()
    info_sheet(wb, "Detailed Analysis", ctx, [("Filter", d.filt.describe())])
    _kpi_sheet(wb, d)
    rows_sheet(wb.create_sheet("Activities"), d.rows, FULL_COLS, ctx.data_date)
    rows_sheet(wb.create_sheet("Lookahead"), d.lookahead, LOOKAHEAD_COLS, ctx.data_date)
    crit = [r for r in d.rows if r.is_critical or r.is_longest_path or r.is_near_critical]
    rows_sheet(wb.create_sheet("Critical"), crit, CRIT_COLS, ctx.data_date)
    _milestone_sheet(wb, d.milestones)
    _evm_sheet(wb, d)
    _changes_sheet(wb, cache.changes)
    _health_sheet(wb, cache.health)
    _validation_sheet(wb, *cache.validation)
    if audit:
        _audit_sheet(wb, audit)
    wb.save(path)


def export_lookahead(path, d, weeks_list=(2, 4, 6, 8)) -> None:
    ctx = d.ctx
    wb = Workbook()
    info_sheet(wb, "Lookahead", ctx, [("Filter", d.filt.describe())])
    for w in weeks_list:
        rows_sheet(wb.create_sheet(f"{w}-Week Lookahead"), lookahead(ctx, d.rows, w), LOOKAHEAD_COLS, ctx.data_date)
    wb.save(path)


def export_critical(path, d) -> None:
    ctx = d.ctx
    wb = Workbook()
    info_sheet(wb, "Critical Activities", ctx, [("Critical definition", ctx.critical_info["source"]),
                                                ("Longest path source", ctx.critical_info["longest_path_source"])])
    rows_sheet(wb.create_sheet("Critical"), [r for r in d.rows if r.is_critical], CRIT_COLS, ctx.data_date)
    rows_sheet(wb.create_sheet("Longest Path"), [r for r in d.rows if r.is_longest_path], CRIT_COLS, ctx.data_date)
    rows_sheet(wb.create_sheet("Near Critical"), [r for r in d.rows if r.is_near_critical], CRIT_COLS, ctx.data_date)
    rows_sheet(wb.create_sheet("Negative Float"), [r for r in d.rows if r.tf_d is not None and r.tf_d < 0], CRIT_COLS, ctx.data_date)
    wb.save(path)


def export_baseline(path, d, cache) -> None:
    wb = Workbook()
    info_sheet(wb, "Baseline Comparison", d.ctx)
    _changes_sheet(wb, cache.changes)
    rows_sheet(wb.create_sheet("Variance by Activity"), sorted([r for r in d.rows if r.cur is not None],
               key=lambda r: -(r.finish_var_d or -1e9)),
               ["code", "name", "wbs", "bl_start", "bl_finish", "start", "finish", "start_var", "finish_var", "dur_var", "match", "status"],
               d.ctx.data_date)
    wb.save(path)


def export_health(path, d, cache) -> None:
    wb = Workbook()
    info_sheet(wb, "Schedule Health", d.ctx)
    _health_sheet(wb, cache.health)
    _validation_sheet(wb, *cache.validation)
    wb.save(path)
